menu:
  首页: /
  归档: /archives
  关于: /about
  

widgets:
- search
- category
- tagcloud
- blogroll

excerpt_link: Read More

plugins:
- hexo-generator-feed

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-41207871-1
rss: http://silvasong.com/atom.xml